seed: 42

# --- 1. Models ---
models:
  separate: True
  
  # --- Actor (Policy) ---
  policy:
    class: GaussianMixin
    clip_actions: True
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    network:
      - name: net
        type: MLP
        input: STATES          # Size: 20
        layers: [256, 128, 64]
        activations: elu
    output: ACTIONS            # Size: 10

  # --- Critic 1 (Q1) ---
  critic_1:
    class: DeterministicMixin
    network:
      - name: net
        type: MLP
        input: STATES_ACTIONS  # Size: 30
        layers: [256, 128, 64]
        activations: elu
    output: ONE

  # --- Target Critic 1 (Copy of Q1) ---
  # REQUIRED: Explicitly define the target network
  target_critic_1:
    class: DeterministicMixin
    network:
      - name: net
        type: MLP
        input: STATES_ACTIONS
        layers: [256, 128, 64]
        activations: elu
    output: ONE

  # --- Critic 2 (Q2) ---
  critic_2:
    class: DeterministicMixin
    network:
      - name: net
        type: MLP
        input: STATES_ACTIONS
        layers: [256, 128, 64]
        activations: elu
    output: ONE

  # --- Target Critic 2 (Copy of Q2) ---
  # REQUIRED: Explicitly define the target network
  target_critic_2:
    class: DeterministicMixin
    network:
      - name: net
        type: MLP
        input: STATES_ACTIONS
        layers: [256, 128, 64]
        activations: elu
    output: ONE

# --- 2. Memory ---
memory:
  class: RandomMemory
  memory_size: 100000

# --- 3. SAC Agent ---
agent:
  class: SAC
  
  # Hyperparameters
  gradient_steps: 1
  batch_size: 64
  discount_factor: 0.99
  polyak: 0.005
  
  # Learning Rates
  actor_learning_rate: 3.0e-4
  critic_learning_rate: 3.0e-4

  # Entropy
  learn_entropy: True
  entropy_learning_rate: 3.0e-4
  initial_entropy_value: 0.2

  # Logging
  experiment:
    directory: "right_arm_sac"
    experiment_name: ""
    write_interval: 100
    checkpoint_interval: 5000
    store_separately: False
    wandb: False

# --- 4. Trainer ---
trainer:
  class: SequentialTrainer
  timesteps: 100000
  environment_info: log